---
title: "restaurantR package"
author: "Amit Bhatnagar and Kavitha Balasubramanian"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction 

Factual is an open data platform primarily focused on data for local businesses. Factual database is used by leading players in Local Business information including Facebook, Groupon, and Bing Local search. However, currently there is only minimal support for Factual in R. (There is an unofficial package last updated in 2011 and is not even functional anymore.  https://cran.r-project.org/web/packages/factualR/index.html) Our package allows the user to extract relevant information on local restaurants without needing to know the intricacies of Factual database. 

## Target user persona

The typical persona of this package would be a person working on restaurant research for business uses. An example of this may be a content developer for a restaurant blog or magazine or a person working in new initiatives department of a food chain. 

## Scope and limitations 
For this iteration of the project, we have kept the focus limited to the restaurants in United States only. Also, we are using the free, verified version of Factual, which puts certain limitations on the results returned (Limitations include: 1) Only top 20 results matching a query are returned. 2) There are some limits on queries per minute and queries per day.) These limits can be resolved by an enterprize user by purchasing a business license from Factual. 

## Some examples 


```{r, fig.show='hold'}
rm(list=ls())
library(restaurantR)
getAlcoholFriendlyRestaurants("Mountain View","Indian")

```

Then you can use the chunk option `fig.cap = "Your figure caption."` in **knitr**.

## More Examples


> "He who gives up [code] safety for [code] speed deserves neither."
([via](https://twitter.com/hadleywickham/status/504368538874703872))
